######################################################################
# Automatically generated by qmake (3.0) ?? ??? 8 20:26:04 2015
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = perf_test
INCLUDEPATH += .

# Input
HEADERS += perf_test.h ../jhmi/jitems.h ../jhmi/jview.h ../jhmi/jdefs.h
FORMS += perf_test.ui
SOURCES += main.cpp perf_test.cpp ../jhmi/jview.cpp ../jhmi/jdefs.cpp
RESOURCES += perf_test.qrc
